### ISSUE TITLE
Not working code

### ISSUE THREAD

**Issue by namekinggamerboy** [codingJWilliams/Warm-Welcome#2]

**Comment by codingJWilliams** [comment]
What do you mean by that? Are you getting any errors

**Comment by namekinggamerboy** [comment]
![Screenshot_2020-01-21-08-13-20-365](https://user-images.githubusercontent.com/53903319/72771131-ed3ee500-3c25-11ea-91ba-c796f8084a39.jpeg)
I am use glitch but sir please help me dm me in Discord my discord name:- `⏺️NAME BOY⏺️#2751` my discord name

**Comment by namekinggamerboy** [comment]
![Screenshot_2020-01-21-11-15-18-089](https://user-images.githubusercontent.com/53903319/72778614-744c8700-3c3f-11ea-891c-889041ec64d6.jpeg)
Show me error in aws not found but

![Screenshot_2020-01-21-11-15-36-348](https://user-images.githubusercontent.com/53903319/72778687-a827ac80-3c3f-11ea-8dfc-d38860bfbcc2.jpeg)

**Comment by codingJWilliams** [comment]
You need to add your AWS credentials into that file

**Comment by namekinggamerboy** [comment]
@codingJWilliams  please dm me

**Comment by namekinggamerboy** [comment]
In Discord

**Comment by codingJWilliams** [comment]
Unfortunately, I don't provide DM support.

**Comment by namekinggamerboy** [comment]
But sir I am send my glitch link in project ok so dm me please

**Comment by namekinggamerboy** [comment]
😭😭😭😭😭😭😭😭

**Comment by namekinggamerboy** [comment]
Ok how to create AWS
